<?php

namespace Database\Seeders;

use App\Models\SurveyYear;
use App\Models\StatsPopulationCategory;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class StatPopulationCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public static function run(): void
    {   
        StatsPopulationCategory::insert([
            // berdasarkan yang pindah dan datang
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Pindah',
                'tahun' => '2009',
                'jumlah' => 5,
                'jenis_data' => 'Berdasarkan yang Pindah dan Datang',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Pindah',
                'tahun' => '2010',
                'jumlah' => 17,
                'jenis_data' => 'Berdasarkan yang Pindah dan Datang',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Pindah',
                'tahun' => '2011',
                'jumlah' => 11,
                'jenis_data' => 'Berdasarkan yang Pindah dan Datang',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Pindah',
                'tahun' => '2012',
                'jumlah' => 9,
                'jenis_data' => 'Berdasarkan yang Pindah dan Datang',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Pindah',
                'tahun' => '2013',
                'jumlah' => 18,
                'jenis_data' => 'Berdasarkan yang Pindah dan Datang',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Datang',
                'tahun' => '2009',
                'jumlah' => 1,
                'jenis_data' => 'Berdasarkan yang Pindah dan Datang',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Datang',
                'tahun' => '2010',
                'jumlah' => 21,
                'jenis_data' => 'Berdasarkan yang Pindah dan Datang',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Datang',
                'tahun' => '2011',
                'jumlah' => 6,
                'jenis_data' => 'Berdasarkan yang Pindah dan Datang',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Datang',
                'tahun' => '2012',
                'jumlah' => 8,
                'jenis_data' => 'Berdasarkan yang Pindah dan Datang',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Datang',
                'tahun' => '2013',
                'jumlah' => 21,
                'jenis_data' => 'Berdasarkan yang Pindah dan Datang',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], 

            // berdasarkan mata pencaharian
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Pertanian',
                'tahun' => '2009',
                'jumlah' => 1600,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Pertanian',
                'tahun' => '2010',
                'jumlah' => 1700,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Pertanian',
                'tahun' => '2011',
                'jumlah' => 2500,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Pertanian',
                'tahun' => '2012',
                'jumlah' => 2500,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Pertanian',
                'tahun' => '2013',
                'jumlah' => 2100,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Industri',
                'tahun' => '2009',
                'jumlah' => 0,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Industri',
                'tahun' => '2010',
                'jumlah' => 0,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Industri',
                'tahun' => '2011',
                'jumlah' => 500,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Industri',
                'tahun' => '2012',
                'jumlah' => 500,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Industri',
                'tahun' => '2013',
                'jumlah' => 0,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], 
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Perdagangan',
                'tahun' => '2009',
                'jumlah' => 300,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Perdagangan',
                'tahun' => '2010',
                'jumlah' => 300,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Perdagangan',
                'tahun' => '2011',
                'jumlah' => 1000,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Perdagangan',
                'tahun' => '2012',
                'jumlah' => 500,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Perdagangan',
                'tahun' => '2013',
                'jumlah' => 100,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], 
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'PNS',
                'tahun' => '2009',
                'jumlah' => 0,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'PNS',
                'tahun' => '2010',
                'jumlah' => 0,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'PNS',
                'tahun' => '2011',
                'jumlah' => 0,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'PNS',
                'tahun' => '2012',
                'jumlah' => 0,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'PNS',
                'tahun' => '2013',
                'jumlah' => 0,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], 
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Angkutan',
                'tahun' => '2009',
                'jumlah' => 0,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Angkutan',
                'tahun' => '2010',
                'jumlah' => 200,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Angkutan',
                'tahun' => '2011',
                'jumlah' => 300,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Angkutan',
                'tahun' => '2012',
                'jumlah' => 300,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Angkutan',
                'tahun' => '2013',
                'jumlah' => 400,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], 
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Lainnya',
                'tahun' => '2009',
                'jumlah' => 500,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Lainnya',
                'tahun' => '2010',
                'jumlah' => 600,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Lainnya',
                'tahun' => '2011',
                'jumlah' => 700,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Lainnya',
                'tahun' => '2012',
                'jumlah' => 700,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'survey_id' => self::getSurveyId(),
                'label' => 'Lainnya',
                'tahun' => '2013',
                'jumlah' => 100,
                'jenis_data' => 'Berdasarkan Mata Pencaharian',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], 
        ]);
    }

    public static function getSurveyId()
    {
        return SurveyYear::first()->id;
    }
}
